export interface Hardware {
    inventory_plate: string,
    serial: string,
    cost: number,
    months_warranty: number,
    brand: string,
    creation_date_hv: string,
    status: string,
    buy_date: string,
    provider: string,
    model: string,
    type_hardware: string,
    users_id_user: number,
    hardware_inventory_plate: string,
    assignment_date: string,
    id_user: number,
    email: string,
    first_name: string,
    last_name: string,
    password: string,
    password_changed_date: string,
    type_user: string,
    failed_attempts: number,
    dependencies_id_dependencie: number,
    id_dependencie: number,
    name_dependencie: string
}